run_profile_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: tu22760.ap-south-1.aws
      # User/password auth
      user: _user_
      password: _password_
      authenticator: username_password_mfa
      role: ACCOUNTADMIN
      database: ONBE_DEMO_DEV
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False
      query_tag: snowflake
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
    main:
      type: snowflake
      account: tu22760.ap-south-1.aws
      # User/password auth
      user: _user_
      password: _password_
      authenticator: username_password_mfa
      role: ACCOUNTADMIN
      database: ONBE_DEMO_PROD
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False
      query_tag: snowflake
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
