name: Check Prophecy minor version

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}
  cancel-in-progress: true

jobs:
  compare_minor_version:
    name: compare minor version; maybe bump it
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git branch --list -v
      - uses: actions/setup-python@19e4675e06535f6b54e894da5c1f044400bb4996
        # this SHA is post-5.4.0 to get `.tool-versions` support from PR #1043
        id: setup
        with:
          python-version-file: '.tool-versions'
          cache: 'pipenv'
      # - name: Set up environment variables
      #   run: |
          # echo "PROJECT_SUBPATH=." >> $GITHUB_ENV
          # echo "CHANGE_TARGET=${{ github.base_ref || github.ref_name }}" >> $GITHUB_ENV
      - name: Install `pipenv`, etc.
        run: |
          pip install 'pipenv==v2024.4.1' --user
          pipenv install
      - run: |
          echo -n "Setup cache hit? : "
          echo ${{ steps.setup.outputs.cache-hit }}
      - name: Run versioning check and commit if changed
        run: |
          if ! pipenv run \
            pbt versioning \
              --path . \
              --compare "${{ github.base_ref }}"
          then
              pipenv run \
                pbt versioning \
                  --path . \
                  --compare "${{ github.base_ref }}" \
                  --bump minor
              git config \
                --global user.name "github-actions[bot]"
              git config \
                --global user.email \
                  "github-actions[bot]@users.noreply.github.com"
              # git add "$PROJECT_SUBPATH"
              git add "${{ github.workspace }}"
              git commit -m "Auto bump minor version"
              git push
              exit 1  # Fail the job to indicate changes were needed
          fi
