name: Run `dbt` via GitHub Actions
on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]

jobs:
  run_dbt_tests:
    name: Run DBT tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: 'Install Python via `asdf`'
        uses: asdf-vm/actions/install@v3.0.2
      - uses: tiagovrtr/actions-pipenv@v1
        with:
          pipenv-version: 'v2024.4.1'
      - name: 'Install `dbt` via pipenv'
        run: pipenv install --sync
      - name: 'run the tests'
        id: dbt-test
        run: dbt test
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_PROFILE:  ${{ github.base_ref }}
          DBT_PROFILES_DIR: .
      - name: Show the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-test.outputs.result }}"
        shell: bash
