name: Run `dbt` via GitHub Actions
on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]
  push:
    branches:
      - dev-gha

jobs:
  run_dbt_tests:
    name: Run DBT tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: 'Install asdf'
        uses: ynab/asdf-action@v1.2
        with:
          version: 0.16.1
      - name: 'Install Python via `asdf`'
        id: asdf
        run: |
          asdf plugin add python https://github.com/asdf-community/asdf-python
          asdf install python
          asdf current python
      # - run: echo "${{ steps.asdf.outputs.result }}"
      - name: 'Install `pipenv`'
        uses: tiagovrtr/actions-pipenv@v1
        with:
          pipenv-version: 'v2024.4.1'
      - name: 'Install `dbt`, etc. via `pipenv`'
        run: pipenv install
      - name: 'Run the tests'
        id: dbt-test
        run: pipenv run dbt test
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_PROFILE:  ${{ github.base_ref }}
          DBT_PROFILES_DIR: .
      - name: 'Show the result'
        if: ${{ always() }}
        run: echo "${{ steps.dbt-test.outputs.result }}"
        shell: bash
