name: Run dbt tests
on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize]

jobs:
  run_dbt_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test"
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_PROFILE:  ${{ github.base_ref }}
          DBT_PROFILES_DIR: .
